name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./doc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install plantuml
        run: sudo apt-get install -y plantuml
      - name: Sphinx build
        run: make html
      - name: Copy redirection index.html
        run: cp gh-pages/index.html build/html/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html/
          force_orphan: true